apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${APP_NAMESPACE}
resources:
  - ../../../templates/ceph
  - app.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - config/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
