apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: thanos
  namespace: flux-system
spec:
  path: "./core/monitoring/thanos/app"
  dependsOn:
    - name: minio
    - name: traefik
    - name: rook-ceph
    - name: prometheus-crds
