apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: solaredge
  namespace: flux-system
spec:
  path: "./apps/solaredge/app"
  dependsOn:
    - name: influxdb
  postBuild:
    substitute:
      APP_NAME: solaredge
      APP_NAMESPACE: home-automation
