apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  path: "./core/database/postgres/operator"
  dependsOn:
    - name: prometheus-crds
    - name: rook-ceph
