# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: database
  annotations:
    meta.helm.sh/release-namespace: "database"
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: 20.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system

  values:

    global:
      redis:
        password: "${SECRET_DATABASE_PASSWORD}"
      compatibility:
        openshift:
          adaptSecurityContext: disabled

    nameOverride: "redis"
    fullnameOverride: "redis"
    clusterDomain: cluster.local
    useHostnames: true
    nameResolutionThreshold: 5
    nameResolutionTimeout: 5
    diagnosticMode:
      enabled: false
      command:
        - sleep
      args:
        - infinity

    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 7.2.5-debian-12-r4
      pullPolicy: IfNotPresent
      debug: false

    architecture: replication
    auth:
      enabled: true
      sentinel: true
      usePasswordFiles: false
      usePasswordFileFromSecret: true

    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      save ""

    master:
      count: 1
      revisionHistoryLimit: 3
      disableCommands:
        - FLUSHDB
        - FLUSHALL
      enableServiceLinks: true
      containerPorts:
        redis: 6379

      startupProbe:
        enabled: false
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      
      livenessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      
      readinessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      
      resourcesPreset: "nano"
      
      podSecurityContext:
        enabled: true
        fsGroupChangePolicy: Always
        fsGroup: 1001
     
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      
      kind: StatefulSet
      updateStrategy:
        type: RollingUpdate
      
      minReadySeconds: 0
      automountServiceAccountToken: false
      shareProcessNamespace: false
      podAntiAffinityPreset: soft
      dnsPolicy: "ClusterFirst"
      persistence:
        enabled: true
        path: /data
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: false
        whenScaled: Retain
        whenDeleted: Retain

      service:
        type: ClusterIP
        labels:
          ip-addr: "true"
        portNames:
          redis: "tcp-redis"
        ports:
          redis: 6379
        nodePorts:
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
        sessionAffinity: None

      terminationGracePeriodSeconds: 30
      serviceAccount:
        create: true
        name: "redis-master"
        automountServiceAccountToken: false

      pdb:
        create: true

    replica:
      kind: StatefulSet
      replicaCount: 3
      revisionHistoryLimit: 10
      disableCommands:
        - FLUSHDB
        - FLUSHALL
      enableServiceLinks: true
      externalMaster:
        enabled: false
        port: 6379
      containerPorts:
        redis: 6378

      startupProbe:
        enabled: true
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 22
      
      livenessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      
      readinessProbe:
        enabled: true
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      
      resourcesPreset: "nano"
      
      podSecurityContext:
        enabled: true
        fsGroupChangePolicy: Always
        fsGroup: 1001
      
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      
      updateStrategy:
        type: RollingUpdate

      minReadySeconds: 0
      automountServiceAccountToken: false

      dnsPolicy: "ClusterFirst"
      persistence:
        enabled: true
        path: /data
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: false
        whenScaled: Retain
        whenDeleted: Retain
      
      service:
        type: ClusterIP
        labels:
          ip-addr: "true"
        ports:
          redis: 6378
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
        sessionAffinity: None
     
      terminationGracePeriodSeconds: 30
      autoscaling:
        enabled: false

      serviceAccount:
        create: true
        name: "redis-replica"
        automountServiceAccountToken: false
      
      pdb:
        create: true

    sentinel:
      enabled: false

    serviceBindings:
      enabled: false

    networkPolicy:
      enabled: true
      allowExternal: true
      allowExternalEgress: true

      metrics:
        allowExternal: true

    podSecurityPolicy:
      create: true
      enabled: true

    rbac:
      create: true
    serviceAccount:
      create: true
      automountServiceAccountToken: false
    tls:
      enabled: false
      authClients: true
      autoGenerated: false

    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/redis-exporter
        tag: 1.62.0-debian-12-r2
        pullPolicy: IfNotPresent
      containerPorts:
        http: 9121
      startupProbe:
        enabled: false
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      livenessProbe:
        enabled: true
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      redisTargetHost: "localhost"
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      resourcesPreset: "micro"

      service:
        enabled: true
        type: ClusterIP
        ports:
          http: 9121
        externalTrafficPolicy: Cluster
      
      serviceMonitor:
        enabled: true
        port: http-metrics
        interval: 30s
        sampleLimit: false
        targetLimit: false
     
      prometheusRule:
        enabled: true
        rules:
          - alert: RedisDown
            expr: redis_up{service="redis-metrics"} == 0
            for: 2m
            labels:
              severity: error
            annotations:
              summary: Redis&reg; instance {{ `{{ $labels.instance }}` }} down
              description: Redis&reg; instance {{ `{{ $labels.instance }}` }} is down
          - alert: RedisMemoryHigh
            expr: >
              redis_memory_used_bytes{service="redis-metrics"} * 100
              /
              redis_memory_max_bytes{service="redis-metrics"}
              > 90
            for: 2m
            labels:
              severity: error
            annotations:
              summary: Redis&reg; instance {{ `{{ $labels.instance }}` }} is using too much memory
              description: |
                Redis&reg; instance {{ `{{ $labels.instance }}` }} is using {{ `{{ $value }}` }}% of its available memory.
          - alert: RedisKeyEviction
            expr: |
              increase(redis_evicted_keys_total{service="redis-metrics"}[5m]) > 0
            for: 1s
            labels:
              severity: error
            annotations:
              summary: Redis&reg; instance {{ `{{ $labels.instance }}` }} has evicted keys
              description: |
                Redis&reg; instance {{ `{{ $labels.instance }}` }} has evicted {{ `{{ $value }}` }} keys in the last 5 minutes. 

    # Init Containers

    volumePermissions:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/os-shell
        tag: 12-debian-12-r27
        pullPolicy: IfNotPresent
      ## allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
      resourcesPreset: "micro"
      containerSecurityContext:
        runAsUser: 0

    kubectl:
      image:
        registry: docker.io
        repository: bitnami/kubectl
        tag: 1.30.3-debian-12-r4
        pullPolicy: IfNotPresent
      command: ["/opt/bitnami/scripts/kubectl-scripts/update-master-label.sh"]
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]

    sysctl:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/os-shell
        tag: 12-debian-12-r27
        pullPolicy: IfNotPresent
      mountHostSys: true
      resourcesPreset: "micro"

    useExternalDNS:
      enabled: false
      annotationKey: external-dns.alpha.kubernetes.io/
