apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP_NAME}-pvc"
  namespace: ${APP_NAMESPACE}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "${PVC_CAPACITY:-1Gi}"
  storageClassName: "ceph-block"
