# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
  annotations:
    meta.helm.sh/release-namespace: "networking"
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 30.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system

  values:
    deployment:
      replicas: 1
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
          - mountPath: /data
            name: data

    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: dns-token-secret
            key: api-token

    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"

    service:
      externalIPs:
        - "${CONFIG_KUBE_VIP_IP}"
  
    logs:
      general:
        level: INFO

      access:
        enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1

    ingressRoute:
      dashboard:
        enabled: false

    certResolvers:
      letsencrypt-prod:
        email: ${SECRET_EMAIL}
        storage: /data/acme.json
        caServer: "https://acme-v02.api.letsencrypt.org/directory"
        dnsChallenge:
          provider: cloudflare

    metrics:
      prometheus:
        entryPoint: metrics

    globalArguments:
      - "--global.checknewversion"

    additionalArguments:
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetescrd.allowCrossNamespace=true"      
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,127.0.0.1/32"

    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        ingressClass: "traefik"

    ports:
      web:
        redirectTo: 
          port: "websecure"
          priority: 10
      websecure:
        tls:
          enabled: true
          options: default
      metrics:
        port: 8082
        expose: false
        exposedPort: 8082

    persistence:
      enabled: true
      existingClaim: "${APP_NAME}-pvc"
      name: data
      path: /data
