apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-db
  namespace: flux-system
spec:
  path: "./templates/postgres"
  dependsOn:
    - name: postgres-operator
  postBuild:
    substitute:
      APP_NAME: authelia
      APP_NAMESPACE: authentication
      POSTGRES_DATABASE: "authelia"
      POSTGRES_BOOTSTRAP_CMD: "initdb"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  path: "./core/authentication/authelia/app"
  dependsOn:
    - name: traefik
    - name: lldap
    - name: authelia-db
  postBuild:
    substitute:
      APP_NAME: authelia
      APP_NAMESPACE: authentication
