# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: networking
  annotations:
    meta.helm.sh/release-namespace: "networking"
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.15.3
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system

  values:
    crds:
      enabled: true
    replicaCount: 1
    enableCertificateOwnerRef: true
    ingressShim:
      defaultIssuerName: letsencrypt-prod
      defaultIssuerKind: cluster-issuer

    webhook:
      enabled: true

    cainjector:
      enabled: true
      replicaCount: 1

    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring

