apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-hostpath-temp
  namespace: flux-system
spec:
  path: "./core/storage/local-path/operator"
  dependsOn:
    - name: snapshot-controller
  postBuild:
    substitute:
      STORAGE_CLASS_NAME: local-temp
      PATH_POSTFIX: temp
      RECLAIM_POLICY: Delete
