apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  path: "./core/monitoring/prometheus-stack/crds"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph
    - name: traefik
    - name: thanos
    - name: prometheus-crds
  path: "./core/monitoring/prometheus-stack/app"
