apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  path: "./core/monitoring/loki-stack/app"
  dependsOn:
    - name: rook-ceph
