apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pgadmin
  namespace: flux-system
spec:
  path: "./core/database/pgadmin/app"
  dependsOn:
    - name: prometheus-crds
    - name: rook-ceph
